import React, { useState } from 'react';
import PageHeader from '../../../components/ui/PageHeader';
import KPICardRow from '../../../components/ui/KPICardRow';
import KPICard from '../../../components/ui/KPICard';
import SearchFilterBar from '../../../components/ui/SearchFilterBar';
import ChartCard from '../../../components/ui/ChartCard';
import DataTable from '../../../components/ui/DataTable';
import Pagination from '../../../components/ui/Pagination';
import ActionMenu from '../../../components/ui/ActionMenu';
import Badge from '../../../components/ui/Badge';
import { 
  IconReport, IconReportAnalytics, IconReportMoney, IconUsers, 
  IconShield, IconChartBar, IconChartPie, IconChartLine, IconDownload
} from '@tabler/icons-react';

const mockReports = [
  { id: 'REP001', name: 'Revenue Summary Q1', description: 'Complete revenue breakdown for Q1 2026', generatedOn: '2026-07-23', generatedBy: 'Admin User', type: 'Financial' },
  { id: 'REP002', name: 'Player Performance', description: 'Top performing players across all tournaments', generatedOn: '2026-07-22', generatedBy: 'System', type: 'Performance' },
  { id: 'REP003', name: 'Team Spending Analysis', description: 'Spending patterns of active teams', generatedOn: '2026-07-21', generatedBy: 'Finance Dept', type: 'Financial' },
  { id: 'REP004', name: 'Auction Engagement', description: 'Bidder engagement metrics during live auctions', generatedOn: '2026-07-20', generatedBy: 'Admin User', type: 'Engagement' },
  { id: 'REP005', name: 'System Error Log', description: 'Weekly summary of system errors and warnings', generatedOn: '2026-07-19', generatedBy: 'System', type: 'Technical' },
];

export default function ReportsPage() {
  const [searchTerm, setSearchTerm] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const totalPages = 5;

  const handleExport = () => {
    console.log('Exporting report...');
  };

  const columns = [
    { key: 'name', label: 'Report Name' },
    { key: 'description', label: 'Description' },
    { 
      key: 'type', 
      label: 'Type',
      render: (val) => (
        <Badge variant={val === 'Financial' ? 'success' : val === 'Technical' ? 'error' : 'info'}>
          {val}
        </Badge>
      )
    },
    { key: 'generatedOn', label: 'Generated On' },
    { key: 'generatedBy', label: 'Generated By' },
    {
      key: 'actions',
      label: 'Actions',
      render: (_, row) => (
        <ActionMenu 
          actions={[
            { label: 'View Details', onClick: () => console.log('View', row.id) },
            { label: 'Download PDF', onClick: () => console.log('Download', row.id), icon: <IconDownload size={16} /> },
            { label: 'Delete', onClick: () => console.log('Delete', row.id), variant: 'danger' }
          ]}
        />
      )
    }
  ];

  return (
    <div className="space-y-6">
      <PageHeader 
        title="Reports" 
        subtitle="View and analyze system reports and metrics"
        primaryAction={{ label: 'Export Report', onClick: handleExport, icon: <IconReport size={18} /> }}
      />

      <KPICardRow>
        <KPICard title="Total Auctions" value="45" icon={<IconReportAnalytics />} trend={{ value: 12, label: 'vs last month' }} />
        <KPICard title="Total Revenue" value="$2.4M" icon={<IconReportMoney />} trend={{ value: 8, label: 'vs last month' }} />
        <KPICard title="Total Bids" value="12,450" icon={<IconChartBar />} trend={{ value: 15, label: 'vs last month' }} />
        <KPICard title="Total Players" value="1,240" icon={<IconUsers />} />
        <KPICard title="Active Teams" value="32" icon={<IconShield />} />
      </KPICardRow>

      <SearchFilterBar 
        searchPlaceholder="Search reports..."
        searchValue={searchTerm}
        onSearchChange={setSearchTerm}
        filters={[
          {
            id: 'type',
            label: 'Report Type',
            options: [
              { value: 'all', label: 'All Types' },
              { value: 'financial', label: 'Financial' },
              { value: 'performance', label: 'Performance' }
            ],
            value: 'all',
            onChange: () => {}
          },
          {
            id: 'date',
            label: 'Date Range',
            options: [
              { value: 'all', label: 'All Time' },
              { value: 'today', label: 'Today' },
              { value: 'week', label: 'This Week' }
            ],
            value: 'all',
            onChange: () => {}
          }
        ]}
      />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <ChartCard title="Revenue Overview" subtitle="Monthly revenue trends">
          <div className="flex items-center justify-center h-64 bg-gray-50 text-gray-400 rounded-md border border-dashed border-gray-200">
            <div className="flex flex-col items-center gap-2">
              <IconChartLine size={48} className="opacity-20" />
              <span>Line Chart Placeholder</span>
            </div>
          </div>
        </ChartCard>
        <ChartCard title="Top Teams by Spending" subtitle="Distribution of budget">
          <div className="flex items-center justify-center h-64 bg-gray-50 text-gray-400 rounded-md border border-dashed border-gray-200">
            <div className="flex flex-col items-center gap-2">
              <IconChartPie size={48} className="opacity-20" />
              <span>Pie Chart Placeholder</span>
            </div>
          </div>
        </ChartCard>
        <ChartCard title="Bids Overview" subtitle="Bids per auction">
          <div className="flex items-center justify-center h-64 bg-gray-50 text-gray-400 rounded-md border border-dashed border-gray-200">
             <div className="flex flex-col items-center gap-2">
              <IconChartBar size={48} className="opacity-20" />
              <span>Bar Chart Placeholder</span>
            </div>
          </div>
        </ChartCard>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
        <div className="p-5 border-b border-gray-200 flex justify-between items-center">
          <h3 className="text-lg font-semibold text-gray-900">Generated Reports</h3>
        </div>
        <DataTable columns={columns} data={mockReports} />
        <div className="p-4 border-t border-gray-200">
          <Pagination 
            currentPage={currentPage}
            totalPages={totalPages}
            onPageChange={setCurrentPage}
          />
        </div>
      </div>
    </div>
  );
}
